version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcadia-web
    volumes:
      - ./public:/var/www/html           
      - ./classes:/var/www/classes      
    ports:
      - "8031:80"
    networks:
      - arcadia-network

  db:
    image: mysql:8
    container_name: arcadia-db
    environment:
      MYSQL_ROOT_PASSWORD: WildLifeSecure33!
      MYSQL_USER: KeeperAdmin
      MYSQL_PASSWORD: WildLifeSecure33!
      MYSQL_DATABASE: arcadia
    volumes:
      - db_data:/var/lib/mysql
     #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - arcadia-network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: arcadia-phpmyadmin
    environment:
      PMA_HOST: arcadia-db
      MYSQL_ROOT_PASSWORD: WildLifeSecure33!
    ports:
      - "9080:80"
    networks:
      - arcadia-network

networks:
  arcadia-network:

volumes:
  db_data:

  